p = input("Enter the Principal amount: ")
r = input("Enter the Rate of intreset per annum: ")
t = input("Enter the time period: ")
n = input("Enter the value of times per year: ")
p= float(p)
r =float(r)
t= float(t)
n = float(n)
sum = p * (1 +r/(100*n)) ** (n * t)
print("Your value: ",sum)
